### ISSUE TITLE
Allow specifying a different directory for `.clean` files before renaming them

### ISSUE THREAD

**Issue by zx8** [mikenye/docker-striparr#12]
I'm using Striparr with Sonarr/Radarr and it works great. 👍 

The problem is with Plex – it seems to sometimes get confused when there are 2 files in the same directory with the same names. More often than not there's no issue, but occasionally I have to manually force a re-scan my library to fix it.

I'm not sure what combination of events triggers this issue with Plex, but I do know it's something to do with renaming/deleting files with the same name in quick succession.

It would be great if Striparr, as a workaround, could add an option to use a temporary/different directory outside of Plex to process the cleaned file (e.g. `/tmp/<random-filename>`) then move it back/overwrite the original.

**Comment by mikenye** [comment]
I've implemented this in branch `issue_12` and am currently testing.

**Comment by mikenye** [comment]
OK, this has been implemented! Pull the latest version and recreate your container. I hope this solves your problem. Thanks for the suggestion!

**Comment by zx8** [comment]
Thank you!
