### ISSUE TITLE
Mass Processing Files

### ISSUE THREAD

**Issue by angrycuban13** [mikenye/docker-striparr#15]
Hi,

I couldn't find a way to "mass process" existing files and using tab autocompletion on any existing library would take quite a bit of time.

I couldn't get it to work with bash for some reason but managed to hack something up on Powershell. I don't know if you are interested in adding it on the `README.md`

Paths would need to be changed in a per user's basis. Also keep in mind, I'm running these Powershell comamnds on the root of the drive where my media is. If you wish to not do that, you'd just need to adjust the path for where your `media.txt` will be output to.

```powershell
#First we find all our .mkv files
Get-ChildItem -Recurse -Filter '*.mkv' | Group-Object "FullName" | Select-Object Name  | Out-File media.txt
````
```powershell
#Now we need to change the Windows path to where Stripparr expects the media to be
(Get-Content .\media.txt -Raw) -replace [Regex]::Escape('X:\'), '/storage/media/' | Out-File media.txt
```
```powershell
#We have some more replacing to do
(Get-Content .\media.txt -Raw) -replace [Regex]::Escape('\'), '/' | Out-File media.txt    
```
```powershell
#We need to surround every line with quotation marks to account for spaces
(Get-Content .\media.txt) -replace '^|$', '"' | Out-File .\media.txt
```
Afterwards, I manually grabbed the `manually_process.py` file from my appdata folder or you can get it from [here](https://github.com/mikenye/docker-striparr/blob/master/rootfs/manually_process.py) and modified [line 34](https://github.com/mikenye/docker-striparr/blob/master/rootfs/manually_process.py#L34) to point to where Striparr is listening on my docker host:
```python
r = requests.post('http://192.168.4.15:40000/', json=request_json)
```
And last but not least, we send the request to Striparr:
```powershell
$movies = [System.IO.File]::ReadLines(".\media.txt")

foreach ($movie in $movies) {
    python.exe .\scripts\python\remove_metadata.py $movie
}
```

Originally I had done the first portion in bash thanks to @tronyx. Here's how:
```bash
#Change the path to where your media resides on the host
find /mnt/media/ -name "*.mkv" > media.txt

#Change the media paths to where the container expects the media to be
sed -i 's|/mnt/media|/storage/media|g' media.txt

#Surround each line with "" to account for spaces
sed -i 's/\(.*\)/"\1"/g' media.txt
```

**Comment by mikenye** [comment]
Very ingenious of you - nice work.

Would you mind if I updated the readme linking to this issue?

**Comment by angrycuban13** [comment]
Not at all, please do!

The bash portion could not be possibly without the help of @tronys

**Comment by mikenye** [comment]
Thanks!

**Comment by DrSeussFreak** [comment]
I run linux, so I wrote a simple bash script to utilize the commands above, added a loop and I ran this from within my container.  This worked for me!

```
#!/bin/bash

find /media/videos/TV/ /media/videos/Movies/ /media/videos/Kids\ Movies/ /media/videos/Kids\ TV/ -name "*.mkv" > media.txt
find /media/videos/TV/ /media/videos/Movies/ /media/videos/Kids\ Movies/ /media/videos/Kids\ TV/ -name "*.mp4" >> media.txt 
find /media/videos/TV/ /media/videos/Movies/ /media/videos/Kids\ Movies/ /media/videos/Kids\ TV/ -name "*.avi" >> media.txt 

file="media.txt"
while IFS= read line
do
        "/manually_process.py" echo "$line"
done <"$file"
```

**Comment by tronyx** [comment]
You can simplify your find command greatly as follows:

```
find /media/TV/ /media/Movies/ -type f \( -iname \*.mkv -o -iname \*.mp4 \) > media.txt
```

**Comment by DrSeussFreak** [comment]
I was playing around with it, but got lazy ;)  I just updated my comment

**Comment by felipefmartinez** [comment]
for bash you can do this pretty simply by going into the docker with: 

docker exec -it striparr sh


once in there you can ls around and find your media. let's assume I have all my media in a folder called media for the sake of this exercise.


now you can easily strip all mkvs like this, one line.

find /media -type f -exec /manually_process.py {} \;


this will process all files in the /media folder. if you want to only process mkv adjust it like so

find /media -type f -name '*.mkv' -exec /manually_process.py {} \;
