### ISSUE TITLE
docker.img filling up

### ISSUE THREAD

**Issue by HStep20** [mikenye/docker-striparr#25]
Just had my containers crash because my docker.img filled up. I expect the case is that it was transcoding/remuxing into the .img, and there wasn't enough room left for the large movie file.

Is there a common path that it always transcode at, so I can map it to a volume on an ssd? I did a quick skim of the script, but didn't see anything that stood out path-wise for a transcoding directory.

**Comment by mikenye** [comment]
It does transcode into the `/tmp` of the container, then moves the transcoded file over the top of the original file upon success.

Can I trouble you to run `docker exec -it striparr find /tmp` and post the output (if not sensitive)? That way we can determine if your `/tmp` is filling up for some reason.

**Comment by HStep20** [comment]
Yep, I found it. 

My issue was that /tmp was located inside my space limited docker image. Now that I know it transcodes to '/tmp', I've mapped it to a folder outside of the .img, so it doesn't fill up. Thanks!

**Comment by mikenye** [comment]
I'm glad that's solved your problem. :)
